# Generated by Django 4.1.4 on 2022-12-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=129)),
                ('last_name', models.CharField(max_length=129)),
                ('email', models.EmailField(max_length=129, unique=True, verbose_name='email address')),
                ('phone_number', models.PositiveBigIntegerField(max_length=15)),
                ('joined_on', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
